apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: ${AWS_REGION}
  version: "1.23"

availabilityZones: ["${AZS[0]}", "${AZS[1]}", "${AZS[2]}"]

managedNodeGroups:
- name: eks-example
  desiredCapacity: 3
  instanceType: t3.small
  ssh:
    enableSsm: true

secretsEncryption:
  keyARN: ${MASTER_ARN}
